# Generated by Django 3.2.6 on 2021-08-31 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='fkey',
            new_name='name',
        ),
    ]
