# Generated by Django 3.2.6 on 2021-09-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20210905_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=2000),
        ),
    ]
