# Generated by Django 3.2.6 on 2021-09-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_auto_20210915_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_order',
            new_name='product',
        ),
    ]
