# Generated by Django 3.2.6 on 2021-09-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_rename_product_order_order_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='Customer',
        ),
    ]
