# Generated by Django 3.2.6 on 2021-09-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_rename_customer_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Customer',
            new_name='customer',
        ),
    ]
