# Generated by Django 3.2.6 on 2021-09-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0009_rename_customer_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
    ]
